allowBuilds:
  '@google/genai': false
  core-js-pure: false
  esbuild: true
  protobufjs: false
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260918.1'
  - '@cloudflare/vitest-plugin@1.1.13'
  - '@cloudflare/workerd-darwin-64@1.20260918.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260918.1'
  - '@cloudflare/workerd-linux-64@1.20260918.1'
  - '@cloudflare/workerd-linux-arm64@1.20260918.1'
  - '@cloudflare/workerd-windows-64@1.20260918.1'
  - miniflare@5.20260918.0-alpha
  - workerd@1.20260918.1
  - wrangler@4.135.0
